[phases.setup]
aptPkgs = [
    "chromium",
    "chromium-sandbox",
    "fonts-liberation",
    "libappindicator3-1",
    "libasound2",
    "libatk-bridge2.0-0",
    "libatk1.0-0",
    "libcups2",
    "libdbus-1-3",
    "libgbm1",
    "libglib2.0-0",
    "libgtk-3-0",
    "libnspr4",
    "libnss3",
    "libx11-6",
    "libxcomposite1",
    "libxdamage1",
    "libxrandr2"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "npm start"

